---
title: "Bolsa de valores"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyquant)

prices <- c(
  "PETR4","ABEV3", "BRAP4", "MGLU3", "VOWG3", "AMZO34"
  ) %>%
  paste0(".SA") %>%
  tq_get(get="stock.prices", from = "2020-01-01")%>%
  mutate(symbol = sub(".SA","", symbol))

tabela_periodo <- data.frame( 
  periodo = c("1M", "6M", "1A"), 
  dias = c(30,180,365)
    )
```

Column {.sidebar}
--------------------------------------------------------------------------------------
```{r}
selectInput(
  "action", label = "Escolha o Título", choices = c("PETR4","ABEV3", "BRAP4", "MGLU3", "VOWG3", "AMZO34"))
selectInput (
  "periodo", label = "Período de Busca", choices = c ( "1M", "6M", "1A" ))
```

Row{data-width=350}
-----------------------------------------------------------------------

```{r}
renderPlotly({
periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias

prices %>%
  filter(date >= periodo, symbol == input$action) %>%
  ggplot() +
  aes(x= date, y = adjusted) +
  geom_line()+
  labs(x="", y = "Cotação") +
  ggtitle(label = input$action)+
  theme_classic( )
  
})
```

Row{data-width=350}
-----------------------------------------------------------------------

```{r}
renderPlotly({
periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias

prices %>%
  filter(date >= periodo) %>%
  ggplot() +
  aes(x=date, y=adjusted, color=symbol)+
  geom_line(size = 1.0)+
  labs( title = "TENDÊNCIA", x="", y= "Cotação", color="Ação")+
  theme(panel.background = element_blank())

})
```

